# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a32ccaa40be6f9ee943104305b3287f6fa9407fea98158a2625a64a1d8034a1dacf4a67ff216a7187ba21305b9eb28eba75d28a07e6667840a87b793ea922b7

test:
  secret_key_base: 8e9343a864fef5e0980f81b5a82dd56e3bcff5242159b5b1ee8ea1ed1e16dd0ab967dbeed2a2c9ba307ddb602bc036419e5d97fd7481aaf1ccabbefbccfcc857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
