# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa660c9fef4ef29cbdaa87f514c02092831f9ae0a7796f7c2ee189fe6a31336e1837fcf15e2af969b1d27d50efbdc69940747ece7225336cdeecae697474609

test:
  secret_key_base: fadcc7c3adc87d809d697da9a22559a7c07cc2764843f0c0d9ea889aafd65eb1c0579763fd19855b83108c143e6885900d36954346d05b1cae20065f99b0cbab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
