# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e704901092a5a19218fb4f7c25eb706571fa2ad7e4028db4fd86166a4ac8d35538e393593e925a9f02cf8df92721fd0a7686846680799087d2f817e6f1b11b

test:
  secret_key_base: 7c65be2e2d2c43e73daa32d38944288932ec8f8b87b1ddbca42e15508d179bc496d5d96cfe9d3182bf23868d70a9e3faa84c46cfeaa207b02b5d3e8361beb698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
